server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: sample_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: sample_service
          host: sample-service-host
          __path__: /app/logs/*.log
